### ISSUE TITLE
Icones won't load properly

### ISSUE THREAD

**Issue by Jejebond** [beecho01/material-symbols#7]
**Describe the bug**
Icones won't load properly, even with navigator cache cleared and the ressource module added: /hacsfiles/material-symbols/material-symbols.js
Same issue on companion app.

**To Reproduce**
1)**Refresh** web page
2)Icones **not showing**
3)Edit dashboard
4)Icones **showing**
5)End edition
6)Icones **showing**
7)**Refresh** web page
8)Icones **not showing**

**Solution**
I've seen [crawmartino](https://community.home-assistant.io/u/crawmartino) telling the same issue : [Material Symbols for Home Assistant - A Material Design 3 based icon pack](https://community.home-assistant.io/t/material-symbols-for-home-assistant-a-material-design-3-based-icon-pack/599573/12)
He is using UI Controlled dashboard too.

**Comment by xvlw** [comment]
Also experiencing this while doing the steps you mention above. I've also tried restarting HA multiple times and it randomly will load or not load after a full HA restart as well.

Clearing browser cache doesn't help either.

**Comment by moonbit5** [comment]
would love to know the cause of this issue – it happens all the time, randomly. Any one know what could be causing it?

**Comment by moonbit5** [comment]
I've found that loading another dashboard briefly then navigating back to the main dashboard brings the icons back. Could be a clue?

Or perhaps is just a cache issue – but does seem like something else is going on under the hood?

**Comment by xvlw** [comment]
> Or perhaps is just a cache issue – but does seem like something else is going on under the hood?

This also works; if you edit dashboard then press "done" it sometimes fixes it. 

If that doesn't fix it, going edit dashboard, go to edit a card (don't have to make any changes), then cancel out of the edit card and press "done" again on the edit dashboard brings them back for awhile until they disappear again on another load

**Comment by moonbit5** [comment]
curious if any of you are experiencing this issue: https://github.com/home-assistant/frontend/issues/17820#issuecomment-2422864729

Feel like this icon issue arrived at a similar time to 'no back'.

If you are experiencing the same issue, let them know on that thread. 

edit: OR if any of you are using bubble cards hacs integration on your dashboards?

**Comment by xvlw** [comment]
> curious if any of you are experiencing this issue: [home-assistant/frontend#17820 (comment)](https://github.com/home-assistant/frontend/issues/17820#issuecomment-2422864729)
> 
> Feel like this icon issue arrived at a similar time to 'no back'.
> 
> If you are experiencing the same issue, let them know on that thread.
> 
> edit: OR if any of you are using bubble cards hacs integration on your dashboards?

I think I have bubble card installed but it's not part of my dashboard.

**Comment by beecho01** [comment]
Hi @Jejebond, @mousemat86, @xvlw,

I have done a major update to this and migrated from Lovelace/Dashboard repository, to an Integration repository.
If you wouldn't mind, please follow the steps in [Migrating from v1.X.X to 202X.X.X](https://github.com/beecho01/material-symbols#migrating-from-v1xx-to-202xxx) and then attempt install via [HACS Method 2](https://github.com/beecho01/material-symbols#hacs-method-2).

Hope this resolves things for you!

Thanks

**Comment by moonbit5** [comment]
Awesome news - will give it a try soon. I've designed a whole set of dashboards around these icons so have been desperate to get a fix rather than editing everything manually. Will report back!

**Comment by moonbit5** [comment]
Great fix – thank you for taking the time @beecho01. 

Find and replace m3s: to m3rf: was a killer :)

**Comment by beecho01** [comment]
I won't be changing the prefix and names again! 😅 This is how I wanted them to begin with but I lacked the knowledge at the time.

I will keep this issue open for now though, to make sure the issues described above do not re-occur.

**Comment by xvlw** [comment]
Do we know when install method 1 will be active. I'd rather not download the custom components if possible.

**Comment by xvlw** [comment]
So far it seems to have fixed my caching issue.

**Comment by Mystically11** [comment]
It looks like this has been fixed on desktop for me, but in the mobile app the icons don't show up at all, no matter if I switch dashboards or reload..

**Comment by beecho01** [comment]
> It looks like this has been fixed on desktop for me, but in the mobile app the icons don't show up at all, no matter if I switch dashboards or reload..

I, too, am seeing this on my Companion App. I have been unable to find the cause for this so I have opened and issue within the Compion App repository:  [https://github.com/home-assistant/android/issues/4834](https://github.com/home-assistant/android/issues/4834).

**Comment by Mystically11** [comment]
> > It looks like this has been fixed on desktop for me, but in the mobile app the icons don't show up at all, no matter if I switch dashboards or reload..
> 
> I, too, am seeing this on my Companion App. I have been unable to find the cause for this so I have opened and issue within the Compion App repository: [home-assistant/android#4834](https://github.com/home-assistant/android/issues/4834).

Turns out all you have to do to fix this is just reinstall the app. Or you can just go into the settings of your phone and clear cache for home assistant (Have not tried this but i'm assuming it would work the same way since reinstalling does it too)

**Comment by xvlw** [comment]
The problem seems to have come back again after upgrading to the latest HA release (not sure if related). I've cleared cache and cookies in browser, removed and re-downloaded the integration, rebooted HA but still happening 2 days later again.

*edit: as of today it seems to be loading again without a problem. Might have been a blip, i'll update if it starts happening again

**Comment by moonbit5** [comment]
Has anyone had issues with icons not loading after the most recent updates? I'm on 2025.2.5

**Comment by mReXiTuS** [comment]
> Has anyone had issues with icons not loading after the most recent updates? I'm on 2025.2.5

yes, I'm on 2025.2.5 and I have this issue of randomly not loading icons for months now.

**Comment by xvlw** [comment]
Also been intermittently having this issue still. Usually going to edit the dashboard then edit any card, saving and exiting the dashboard editor will allow them to show with sometimes having to add a few refreshes.

**Comment by moonbit5** [comment]
I actually think this has been fixed by a cache purge – when I mentioned it the other day I'd been messing about with some custom cards and some theme changes.

Since clearing the cache on my devices, the icons are loading again.

**Comment by xvlw** [comment]
For me clearing cache isn't working.

It works as a solution a fraction of the time but other times its back to the original issue in 2024 where I have to attempt to edit the dashboard to get the icons to show up half the time

**Comment by beecho01** [comment]
Hi @xvlw and @moonbit5,
Unfortunately, I have been struggling to identify what is causing this issue. I have been unable to reproduce this on my setup, which means I have been unable to find the root cause so far.

I have done the following to attempt to reduce the loading issues, so far: 
  - Minified the `material-symbols.js` to reduce the amount of processing that a browser or companion app's webivew needs when loading a page/url.
  - `async_register_static_paths` to use `Cache-Control=True`, should keep the `material-symbols.js`, the multiple `icons.json` and any previously called icon's SVG files. These should persisit in the cache until its cleared or expires. I believe Home Assistants current caching expiration is `Cache-Control: public, max-age=31536000` by default. This is exactly 1 year before the browser will automatically force refresh the cache.
  - The `icons.json` files for each type (i.e. `m3rf`, `m3r` .etc) provides a list of icons, so that Home Assistant doesn't need to generate an icon map on install or during an API call. This could possibly be too big still as this is several thousand lines per icon family type, so systems with limited hardware resources might still struggle. I will continue to investigate this as a potential issue.

If you are willing, could you assist me in getting some more details on how this issue presents for you? It might point me in the right direction!

1. Which version of Home Assistant are you running?
2. How did you install the integration via HACS custom repository or the manual process?
3. Are you accessing Home Assistant through HTTPS or HTTP?
4. Are you using a reverse proxy (like Nginx, Caddy, or Traefik) or something like Cloudflare?
5. Are you using a desktop browser, mobile browser, or the official Home Assistant Companion app?
6. Are all icons missing, or just some icons not appearing?
7. Do icons show up after a refresh or only if you open the Home Assistant editor?
8. If you navigate in your browser to `https://<your-HA>/material_symbols/m3o/10mp.svg` and `https://<your-HA>/material_symbols/m3o/icons.json`, does this show an icon and a json file?
9. If you're able to load the developer options tab (F12 in Chrome); when icons fail to display, do you see any red error messages in the console, any 4xx/5xx errors in the Network tab?
10. Are there any errors or warnings in the Home Assistant logs (Configuration > Logs) related to `material_symbols` or static paths?
11. Have you tried a full browser cache clear or reloading the HA frontend with Ctrl+F5 (desktop) or clearing site data (mobile)?
12. Are you using any other custom icon integrations or resources?
13. Does the icon display issue happen every time, or only intermittently?

**Comment by xvlw** [comment]
Which version of Home Assistant are you running?

![Image](https://github.com/user-attachments/assets/d3d90158-1fe4-4016-a3c5-e361a8da4fbe)

How did you install the integration via HACS custom repository or the manual process?
Custom Repo

Are you accessing Home Assistant through HTTPS or HTTP?
HTTP

Are you using a reverse proxy (like Nginx, Caddy, or Traefik) or something like Cloudflare?
Just the Nabu Casa. Issue is internal as well as external

Are you using a desktop browser, mobile browser, or the official Home Assistant Companion app?
Issue happens on ; Companion App, Firefox Browser and Firefox Progressive Web App. Issue could happen on one device, and not others. Or different icons fail to show up on different devices.

Are all icons missing, or just some icons not appearing?
Some / All. Depends on the reload. It could impact all at once or just some.

Do icons show up after a refresh or only if you open the Home Assistant editor?
Yes and No. Sometimes a refresh fixes all, sometimes only fixes some (a refresh may fix icons not showing in button cards but will fix icons in my menu). What always fixes it is if i edit my dashboard, go to edit a card (dont have to make an actual edit), save the card and exit the dashboard editor.

I have also tried just straight clearing cash and hard reloading and even that is 50/50 if it fixes all icons at once.

There are also odd days where it just always loads. It's very very intermittent.

If you navigate in your browser to https://<your-HA>/material_symbols/m3o/10mp.svg and https://<your-HA>/material_symbols/m3o/icons.json, does this show an icon and a json file?

Results from : https://<your-HA>/material_symbols/m3o/10mp.svg
![Image](https://github.com/user-attachments/assets/6eb49a84-bc67-4fda-8e2e-675065049155)

Results from : https://<your-HA>/material_symbols/m3o/icons.json
![Image](https://github.com/user-attachments/assets/f2ded5ca-19d2-43f9-ab5d-e481d19dfa2b)

If you're able to load the developer options tab (F12 in Chrome); when icons fail to display, do you see any red error messages in the console, any 4xx/5xx errors in the Network tab?

Are there any errors or warnings in the Home Assistant logs (Configuration > Logs) related to material_symbols or static paths?

Console Output

```
MATERIAL SYMBOLS                      2025.01.30  [material_symbols.js:1:1009](http://<IP>:8123/material_symbols/material_symbols.js)
CARD-MOD 3.4.4 IS INSTALLED [card-mod.js:1:52519](http://<IP>:8123/hacsfiles/lovelace-card-mod/card-mod.js)
≡ kiosk-mode             ⋮
version 6.6.0            ⋮ [kiosk-mode.js:1:32785](http://<IP>:8123/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128660)
LAYOUT-CARD 2.4.5 IS INSTALLED [layout-card.js:228:115](http://<IP>:8123/hacsfiles/lovelace-layout-card/layout-card.js?hacstag=156434866245)
  BUTTON-CARD  
 Version 4.1.2 [button-card.js:426:15087](http://<IP>:8123/hacsfiles/button-card/button-card.js?hacstag=146194325412)
 MINI-GRAPH-CARD  0.12.1 [mini-graph-card-bundle.js:1:96068](http://<IP>:8123/hacsfiles/mini-graph-card/mini-graph-card-bundle.js?hacstag=1512800620121)
 MULTIPLE-ENTITY-ROW  4.5.1 [multiple-entity-row.js:1:26787](http://<IP>:8123/hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js?hacstag=178921037451)
vertical-stack-in-card
Version: 1.0.1 [vertical-stack-in-card.js:1:9](http://<IP>:8123/hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js?hacstag=142051833101)
AUTO-ENTITIES 1.13.0 IS INSTALLED [auto-entities.js:172:7850](http://<IP>:8123/hacsfiles/lovelace-auto-entities/auto-entities.js?hacstag=1677445841130)
Loading module from “http://<IP>:8123/browser_mod.js?automatically-added” was blocked because of a disallowed MIME type (“text/plain”).
[0](http://<IP>:8123/dashboard-2024/0)
Loading failed for the module with source “http://<IP>:8123/browser_mod.js?automatically-added”. [0:1:1](http://<IP>:8123/dashboard-2024/0)
Uncaught (in promise) http://<IP>:8123/browser_mod.js?automatically-added
STATE-SWITCH 1.9.5 IS INSTALLED <empty string> [state-switch.js:139:248](http://<IP>:8123/hacsfiles/lovelace-state-switch/state-switch.js?hacstag=158756598195)
  BAR-CARD 
  Version 3.1.7    [bar-card.js:4855:9](http://<IP>:8123/hacsfiles/bar-card/bar-card.js?hacstag=163363577320)
 STACK-IN-CARD 
   Version 0.2.0   [stack-in-card.js:200:5682](http://<IP>:8123/hacsfiles/stack-in-card/stack-in-card.js?hacstag=248954055020)
CARD-TOOLS 2.1.2 IS INSTALLED
  DeviceID: 8f567c76-bd119cfa [card-tools.js:90:4963](http://<IP>:8123/hacsfiles/lovelace-card-tools/card-tools.js?hacstag=16140332811)
  CLOCK-WEATHER-CARD 
 Version: 2.8.10 [clock-weather-card.js:180:260514](http://<IP>:8123/hacsfiles/clock-weather-card/clock-weather-card.js?hacstag=5226340192810)
🍄 Mushroom 🍄 - 4.3.1 [mushroom.js:309:31126](http://<IP>:8123/hacsfiles/lovelace-mushroom/mushroom.js?hacstag=444350375431)
 DECLUTTERING-CARD 
   Version 1.0.0   [decluttering-card.js:186:8155](http://<IP>:8123/hacsfiles/decluttering-card/decluttering-card.js?hacstag=188686483100)
  ---- MY-SLIDER ---- 
  Version 3.0.7    [my-cards.js:186:9668](http://<IP>:8123/hacsfiles/my-cards/my-cards.js?hacstag=399108901106)
  ---- MY-SLIDER-V2 ---- 
  Version 3.0.7    [my-cards.js:356:4347](http://<IP>:8123/hacsfiles/my-cards/my-cards.js?hacstag=399108901106)
  ---- MY-BUTTON ---- 
  Version 1.0.2    [my-cards.js:388:7660](http://<IP>:8123/hacsfiles/my-cards/my-cards.js?hacstag=399108901106)
  ---- MY-CARDS ---- 
  Version 2.0.4    [my-cards.js:495:216](http://<IP>:8123/hacsfiles/my-cards/my-cards.js?hacstag=399108901106)
  HOURLY-WEATHER-CARD 
  Version 6.6.1    [hourly-weather.js:282:1126](http://<IP>:8123/hacsfiles/lovelace-hourly-weather/hourly-weather.js?hacstag=499270202661)
   SWIPE-CARD  
 Version 5.0.0 [swipe-card.js:19:2314](http://<IP>:8123/hacsfiles/swipe-card/swipe-card.js?hacstag=192732887500)
 Bubble Card  v2.4.0 [bubble-card.js:1445:40331](http://<IP>:8123/hacsfiles/Bubble-Card/bubble-card.js?hacstag=680112919240)
 PAPER-BUTTONS-ROW  2.2.0 [paper-buttons-row.js:1367:9](http://<IP>:8123/hacsfiles/lovelace-paper-buttons-row/paper-buttons-row.js?hacstag=244872232220)
light-entity-card v6.1.3 [light-entity-card.js:365:534](http://<IP>:8123/hacsfiles/light-entity-card/light-entity-card.js?hacstag=168744428613)
  SLIDER-BUTTON-CARD  v1.13.0 [slider-button-card.js:1043:451](http://<IP>:8123/hacsfiles/slider-button-card/slider-button-card.js?hacstag=4987940331130)

  RGB Light Card  v1.13.0  
[card.js:350:9](http://<IP>:8123/hacsfiles/rgb-light-card/card.js?hacstag=2153271951130)
SLIDER-ENTITY-ROW 17.4.1 IS INSTALLED <empty string> [slider-entity-row.js:1:61420](http://<IP>:8123/hacsfiles/lovelace-slider-entity-row/slider-entity-row.js?hacstag=1448997001741)
  BIG-SLIDER-CARD 
  Version 1.1.5    [big-slider-card.js:179:215](http://<IP>:8123/hacsfiles/lovelace-big-slider-card/big-slider-card.js?hacstag=332589148115)
 LOGBOOK-CARD  2.5.6 [logbook-card.js:472:185](http://<IP>:8123/hacsfiles/logbook-card/logbook-card.js?hacstag=216008446256)
Loading failed for the module with source “http://<IP>:8123/local/material-rounded-theme.js”. [0:1:1](http://<IP>:8123/dashboard-2024/0)
  Digital-Clock 
  Version 1.2.4    [digital-clock.js:44:63400](http://<IP>:8123/hacsfiles/lovelace-digital-clock/digital-clock.js?hacstag=373832981124)
Uncaught (in promise) http://<IP>:8123/local/material-rounded-theme.js
 CUSTOM-FEATURES-FOR-TILES-AND-MORE v4.2.5 [custom-features-row.min.js:26:92541](http://<IP>:8123/hacsfiles/service-call-tile-feature/custom-features-row.min.js?hacstag=698501153425)
MORE-INFO-CARD 1.2.0 IS INSTALLED <empty string> [more-info-card.js:36:135](http://<IP>:8123/hacsfiles/lovelace-more-info-card/more-info-card.js?hacstag=1805289500994)
 UNIVERSAL-REMOTE-CARD v4.3.12 [universal-remote-card.min.js:50:7579](http://<IP>:8123/hacsfiles/android-tv-card/universal-remote-card.min.js?hacstag=6543936464312)
nathan-gs/ha-map-card: v0.6.0 [map-card.js:381:11](http://<IP>:8123/hacsfiles/ha-map-card/map-card.js?hacstag=734825457060)
The resource at “http://<IP>:8123/static/fonts/roboto/Roboto-Regular.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. [0](http://<IP>:8123/dashboard-2024/0)
Source map error: Error: request failed with status 404
Stack in the worker:networkRequest@resource://devtools/client/shared/source-map-loader/utils/network-request.js:43:9

Resource URL: http://<IP>:8123/hacsfiles/light-entity-card/light-entity-card.js?hacstag=168744428613
Source Map URL: light-entity-card.js.map
```

Network Tab. What am I looking for here? Am I looking for any Status Error that starts with 400 or 500?


Have you tried a full browser cache clear or reloading the HA frontend with Ctrl+F5 (desktop) or clearing site data (mobile)?
I have tried hard F5 refresh, clearing cookies daily ect. Sometimes it works, sometimes it doesn't. This is partially why i kept reporting it fixed then having issues again ect

Are you using any other custom icon integrations or resources?
Card Mod but that's a major one

Entire list of resources below

```
/browser_mod.js?automatically-added
JavaScript module
/hacsfiles/android-tv-card/universal-remote-card.min.js?hacstag=6543936464312
JavaScript module
/hacsfiles/bar-card/bar-card.js?hacstag=163363577320
JavaScript module
/hacsfiles/better-moment-card/better-moment-card.js?hacstag=73702818820250111
JavaScript module
/hacsfiles/Bubble-Card/bubble-card.js?hacstag=680112919240
JavaScript module
/hacsfiles/button-card/button-card.js?hacstag=146194325412
JavaScript module
/hacsfiles/clock-weather-card/clock-weather-card.js?hacstag=5226340192810
JavaScript module
/hacsfiles/decluttering-card/decluttering-card.js?hacstag=188686483100
JavaScript module
/hacsfiles/ha-map-card/map-card.js?hacstag=734825457060
JavaScript module
/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128660
JavaScript module
/hacsfiles/light-entity-card/light-entity-card.js?hacstag=168744428613
JavaScript module
/hacsfiles/logbook-card/logbook-card.js?hacstag=216008446256
JavaScript module
/hacsfiles/lovelace-auto-entities/auto-entities.js?hacstag=1677445841130
JavaScript module
/hacsfiles/lovelace-big-slider-card/big-slider-card.js?hacstag=332589148115
JavaScript module
/hacsfiles/lovelace-card-mod/card-mod.js?hacstag=190927524344
JavaScript module
/hacsfiles/lovelace-card-tools/card-tools.js?hacstag=16140332811
JavaScript module
/hacsfiles/lovelace-digital-clock/digital-clock.js?hacstag=373832981124
JavaScript module
/hacsfiles/lovelace-horizon-card/lovelace-horizon-card.js?hacstag=614083491131
JavaScript module
/hacsfiles/lovelace-hourly-weather/hourly-weather.js?hacstag=499270202661
JavaScript module
/hacsfiles/lovelace-layout-card/layout-card.js?hacstag=156434866245
JavaScript module
/hacsfiles/lovelace-more-info-card/more-info-card.js?hacstag=1805289500994
JavaScript module
/hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js?hacstag=178921037451
JavaScript module
/hacsfiles/lovelace-mushroom/mushroom.js?hacstag=444350375431
JavaScript module
/hacsfiles/lovelace-paper-buttons-row/paper-buttons-row.js?hacstag=244872232220
JavaScript module
/hacsfiles/lovelace-slider-entity-row/slider-entity-row.js?hacstag=1448997001741
JavaScript module
/hacsfiles/lovelace-state-switch/state-switch.js?hacstag=158756598195
JavaScript module
/hacsfiles/mini-graph-card/mini-graph-card-bundle.js?hacstag=1512800620121
JavaScript module
/hacsfiles/mini-media-player/mini-media-player-bundle.js?hacstag=1485208381169
JavaScript module
/hacsfiles/my-cards/my-cards.js?hacstag=399108901106
JavaScript module
/hacsfiles/rgb-light-card/card.js?hacstag=2153271951130
JavaScript module
/hacsfiles/service-call-tile-feature/custom-features-row.min.js?hacstag=698501153425
JavaScript module
/hacsfiles/simple-weather-card/simple-weather-card-bundle.js?hacstag=172998062085
JavaScript module
/hacsfiles/slider-button-card/slider-button-card.js?hacstag=4987940331130
JavaScript module
/hacsfiles/stack-in-card/stack-in-card.js?hacstag=248954055020
JavaScript module
/hacsfiles/swipe-card/swipe-card.js?hacstag=192732887500
JavaScript module
/hacsfiles/upcoming-media-card/upcoming-media-card.js?hacstag=497322919044
JavaScript module
/hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js?hacstag=142051833101
JavaScript module
/hacsfiles/weather-card/weather-card.js?hacstag=192732636150
JavaScript module
/local/material-rounded-theme.js
JavaScript module
```

Does the icon display issue happen every time, or only intermittently?
It happens intermittently but some icons are not showing more often then they all are showing

I'm also happy to get on discord with you if that helps and screenshare, We can poke around a bit and see if that helps

This was a lot of info, hopefully it displays ok

**Comment by xvlw** [comment]
I duno, i was thinking is it possible maybe i didn't do the migration correctly when those changes came out

Could that be contributing to it?

**Comment by beecho01** [comment]
> I duno, i was thinking is it possible maybe i didn't do the migration correctly when those changes came out
> 
> Could that be contributing to it?

I don't think so. The `material-symbols.js` isn't present in your resource list and the console suggests you're running the previous update 2025.01.30 which is only available via the integration.

Thinking about what you have described above and how it appears during/after editor close. I think the editor re-calls the icon lists into cache memory as part of the visual editor configurator. So maybe something isn't being called right before this? 🤔

I have little experience with Firefox currently, but I will test my setup in there shortly, see if I can get the same results. Might be worth looking into `about:cache` in Firefox and see if the max amount is being exceeded somehow? I think, if my memory serves me, there is an option under `about:preferences#privacy` that clears history on close. I think history can include cache in this. Maybe if this is active, the cache is being re-built often?

I'll do my best to test this more soon.

**Comment by xvlw** [comment]
This is what I have for `about:preferences#privacy`

![Image](https://github.com/user-attachments/assets/0a315ea0-0063-4a9e-b34b-c017e7ddcfe7)

This is what I have for `about:cache`

![Image](https://github.com/user-attachments/assets/80efe3aa-281e-4b2e-b636-472ecf944447)

When I click on `List Cache Entries` for Memory on that page I don't see any entries for `/material_symbols/material_symbols.js`

When I click on `List Cache Entries` for disk I see 27 entries for  `/material_symbols/material_symbols.js`

Not sure if any of that helps.

Meanwhile I will run a separate browser with Chrome as a test to see if I have issues with the icons loading on Chrome.

**Comment by xvlw** [comment]
Well, that was a short Chrome test, as soon as I went to reload the page the icons had the same issue

![Image](https://github.com/user-attachments/assets/b235b64d-f0cb-4bd2-95d7-94b1011af498)

vs how it should look

![Image](https://github.com/user-attachments/assets/83e4177e-72f3-443c-81e8-1e3b7a3608e4)

The gear icon on the right that is showing under Settings is from the Font Awesome integration (those always load for whatever reason, no shade just an observation, I prefer the Material Icons)

**Comment by thanasibakis** [comment]
Hi all, wanted to note that I'm seeing the same issue on a fresh install of Home Assistant, but only when connecting via the _internal URL_. Connecting via the external URL (which I have set up through Home Assistant Cloud) does not result in any missing icons.

If testing anything in that scenario would be helpful for debugging, please let me know and I'd be happy to help!

**Comment by xvlw** [comment]
Tested inside my network but using the Nabu Casa external address they provide produces the same results for me after a few refreshes

I also tested using the default theme in case the issue resided with the theme itself and had the same issues

![Image](https://github.com/user-attachments/assets/e88a6607-0075-4585-9637-8d18734d2772)

**Comment by beecho01** [comment]
I have made some changes in the `material_symbols.js` in my latest pre-release `2025.03.15`.
This should add verbose/debug level logs in the console and a few other changes on how the icons are called and cached.

Would you mind installing this pre-release via HACS and testing again?
Would you be able to check the console as before in all log levels (including verbose/debug mode) and see if there are any errors or any new information related (filtered) to `material_symbols.js`? 

Appreciate your help on this 😄!

**Comment by thanasibakis** [comment]
On `2025.03.15`, I don't receive any errors in the log.

One of the icons that doesn't cache properly is `m3o:tv`. The TV icon shows blank on my phone on load. However, if I let the app sit in the background for a few minutes, and then reopen, the icon will indeed show up, and it will remain until a manual refresh of the page.

The log reports the following about `m3o:tv`:

```
2025-03-15 12:59:54.358 DEBUG (SyncWorker_5) [custom_components.material_symbols] Walking directory: /config/custom_components/material_symbols/data/m3o
...
2025-03-15 12:59:55.503 DEBUG (SyncWorker_6) [custom_components.material_symbols] Found icon: tv
...
2025-03-15 12:59:55.589 DEBUG (SyncWorker_6) [custom_components.material_symbols] Final icons list: [... {'name': 'tv'}, ...
2025-03-15 12:59:55.606 DEBUG (MainThread) [custom_components.material_symbols] Icons list served: [... {'name': 'tv'}, ...
```

**Comment by mcrummett** [comment]
Im also seeing this issue. All was fine then I redownloaded the integration as some icons weren't showing search. Now if internal to my network they show blank. But remotely work fine

**Comment by xvlw** [comment]
FYI still seeing the issue with the icons not loading

I've even tried reverting back to the base original theme shipped with HA for a couple days to see if the theme was causing the loading and still had the issue

**Comment by MathisP75** [comment]
Can confirm this is still happening, especially annoying on mobile. It's very random and there's no way to force the icons to refresh.

**Comment by mcrummett** [comment]
I’ve had some success on mobile by clearing the cache Sent from Outlook for iOS From: MathisP75 ***@***.***>Sent: Thursday, April 17, 2025 17:18To: beecho01/material-symbols ***@***.***>Cc: mcrummett ***@***.***>; Comment ***@***.***>Subject: Re: [beecho01/material-symbols] Icones won't load properly (Issue #7) MathisP75 left a comment (beecho01/material-symbols#7)Can confirm this is still happening, especially annoying on mobile. It's very random and there's no way to force the icons to refresh.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.

**Comment by xvlw** [comment]
For fun I removed the integration, removed the HACS install. Rebooted, re-downloaded / reinstalled the HACS repo, set up the integration again, hit a hard refresh CTRL + F5 and still see the issue on PC / Firefox :(

I also use the [Font Awesome](https://github.com/thomasloven/hass-fontawesome) integration to help cover some icons that aren't available in Material Symbols and the Font Awesome ones always load.

I wonder if there is something that can be leveraged from Thomas's implementation here

**Comment by Carsor** [comment]
I have the same problem.
The icons working well in microsoft bing but at HA app doesn't appear.
It's funny that in chrome the icons are showing well.

**Comment by boxedmedia** [comment]
I also have this problem with the Icons.
Safari
1. Clearing the cache
2. Reload --> Icon shown --> Console "Fetched and cached icon bathtub from set m3o"
3. Reload --> Icon not shown --> Console --> No message about the icon - only "Fetched and cached icon list for set m3o/m3r/m3rf and so on"

**Comment by beecho01** [comment]
Hi @boxedmedia,
I will run some tests later this evening and see if I can replicate the issue.
Can I confirm what OS and Browser/App youre using?
Thanks
beecho01

**Comment by boxedmedia** [comment]
> Hi [@boxedmedia](https://github.com/boxedmedia), I will run some tests later this evening and see if I can replicate the issue. Can I confirm what OS and Browser/App youre using? Thanks beecho01

sure @beecho01 ,
macOS 15.5
Safari 18.5 (20621.2.5.11.8)
HomeAssistant 2025.7.3

same problem under the iOS App 2025.7.1

thanks!

**Comment by Carsor** [comment]
Hi,

I'm using home assistant on samsung s22 ultra exnos chip.
The icons doesn't load on this device.

Thanks
Carlos Monteiro

A segunda, 28/07/2025, 10:58, boxedmedia ***@***.***>
escreveu:

**Comment by KidSquid1** [comment]
Has there been any resolution to this issue?  Is it affecting all users or just a sub-set?

Thanks,

Squid
🦑

**Comment by Carsor** [comment]
I bought an S25 ultra with snapdragon chip and now it works very well. Seems the problem is the exnos chip of S22 ultra.
I don't now if more people has this issue.
But the problem happens with the hacs icon too, it don't load on this device.

Thanks

**Comment by bramb85** [comment]
I still have the issue on the iOS app. I have a HA cloud setup but the issue occurs mostly if I'm at home and locally connected. If I open the app (when it's not active in the background) the icons won't show up. Refreshing the screen doesn't always resolve the issue (I sometimes need to do multiple refreshes). What does resolve it is switching to another dashboard and then returning to my default dashboard.

**Comment by mcrummett** [comment]
I’m not sure changing phones is enough to pin this on a specific chipset given the endless other variables at play Sent from Outlook for iOS From: Carsor ***@***.***>Sent: Thursday, August 7, 2025 21:03To: beecho01/material-symbols ***@***.***>Cc: mcrummett ***@***.***>; Comment ***@***.***>Subject: Re: [beecho01/material-symbols] Icones won't load properly (Issue #7) Carsor left a comment (beecho01/material-symbols#7)I bought an S25 ultra with snapdragon chip and now it works very well. Seems the problem is the exnos chip of S22 ultra.
I don't now if more people has this issue.
But the problem happens with the hacs icon too, it don't load on this device.Thanks—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.

**Comment by xvlw** [comment]
Issue still exists for me

**Comment by beecho01** [comment]
Hi All,
In the latest release I have done some major updates to allow for smart retries of icon loading and readiness checks before re-attempting. This should improve the reliability of icons showing.
I have added some better logging too, so if there are still any errors, the console may give me some better clues.
Please update (to https://github.com/beecho01/material-symbols/releases/tag/2025.08.24) and give it a try and let me know if this helps.
Thanks
beecho01

**Comment by Carsor** [comment]
On my Samsung s25 ultra the icons continues to don't appear.

**Comment by boxedmedia** [comment]
> Hi All, In the latest release I have done some major updates to allow for smart retries of icon loading and readiness checks before re-attempting. This should improve the reliability of icons showing. I have added some better logging too, so if there are still any errors, the console may give me some better clues. Please update (to https://github.com/beecho01/material-symbols/releases/tag/2025.08.24) and give it a try and let me know if this helps. Thanks beecho01

Works great for me!

**Comment by KidSquid1** [comment]
@boxedmedia 

What's the best way to upgrade....I'm a bit new to the HA ecosystem.

Thanks,

Squid
🦑

**Comment by beecho01** [comment]
> [@boxedmedia](https://github.com/boxedmedia)
> 
> What's the best way to upgrade....I'm a bit new to the HA ecosystem.
> 
> Thanks,
> 
> Squid 🦑

1) Open HACS from the left-hand menu in Home Assistant.
2) Find the repository with the `Pending` update status.
3) Select the three dots menu on the repository's entry.
4) Choose Redownload from the options and select the latest release.
5) You will need to restart Home Assistant to finalise the update.

**Comment by beecho01** [comment]
> On my Samsung s25 ultra the icons continues to don't appear.

@Carsor have you tried the [troubleshooting](https://github.com/beecho01/material-symbols/blob/main/TROUBLESHOOTING.md) options to clear the cache? An old release may be persisting in the browser cache data or companion app.

**Comment by mcrummett** [comment]
Thanks for the update! I’ve applied it, cleared the cache and immediately it seems to be behaving much better  Sent from Outlook for iOSFrom: James Beeching ***@***.***>Sent: Monday, August 25, 2025 00:02To: beecho01/material-symbols ***@***.***>Cc: mcrummett ***@***.***>; Comment ***@***.***>Subject: Re: [beecho01/material-symbols] Icones won't load properly (Issue #7) beecho01 left a comment (beecho01/material-symbols#7)Hi All,
In the latest release I have done some major updates to allow for smart retries of icon loading and readiness checks before re-attempting. This should improve the reliability of icons showing.
I have added some better logging too, so if there are still any errors, the console may give me some better clues.
Please update and give it a try and let me know if this helps.
Thanks
beecho01—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.

**Comment by Carsor** [comment]
Now it works on A54 5g exnos chip but not work at s25 ultra snapdragon chip. On pc it works well.
Thanks

**Comment by mcrummett** [comment]
The chip won’t have any affect on icons loading properly

**Comment by Carsor** [comment]
I test on my phone the too browsers I use and at the Google Chrome the icons appear well and on Microsoft browser the icons don't appear also on companion app don't appear too. I'm on latest versions of icons and core.

**Comment by ElementZoom** [comment]
Hi there, I just installed this today and also having the same issue. The icon sometimes shows for some sessions, and sometimes they don't load at all. Cleared my cache multiple times, and the issue is appearing randomly on different devices.

**Comment by xvlw** [comment]
> Hi there, I just installed this today and also having the same issue. The icon sometimes shows for some sessions, and sometimes they don't load at all. Cleared my cache multiple times, and the issue is appearing randomly on different devices.

Curious, if you navigate to "settings" from the left pane and back to your main dashboard does it fix it for you?

**Comment by ElementZoom** [comment]
> > Hi there, I just installed this today and also having the same issue. The icon sometimes shows for some sessions, and sometimes they don't load at all. Cleared my cache multiple times, and the issue is appearing randomly on different devices.
> 
> Curious, if you navigate to "settings" from the left pane and back to your main dashboard does it fix it for you?

Thanks for your reply. Currently the icon shows up on computer but not on my HA companion app. I tried to got I settings and unfortunately it didn't fit the issue.

**Comment by xvlw** [comment]
> > > Hi there, I just installed this today and also having the same issue. The icon sometimes shows for some sessions, and sometimes they don't load at all. Cleared my cache multiple times, and the issue is appearing randomly on different devices.
> > 
> > 
> > Curious, if you navigate to "settings" from the left pane and back to your main dashboard does it fix it for you?
> 
> Thanks for your reply. Currently the icon shows up on computer but not on my HA companion app. I tried to got I settings and unfortunately it didn't fit the issue.

Oh if its companion app,  did you try clearing front end cache via the app settings?

Settings > Companion App > Troubleshooting (bottom of page) > Reset Frontend cache

**Comment by ElementZoom** [comment]
> > > > Hi there, I just installed this today and also having the same issue. The icon sometimes shows for some sessions, and sometimes they don't load at all. Cleared my cache multiple times, and the issue is appearing randomly on different devices.
> > > 
> > > 
> > > Curious, if you navigate to "settings" from the left pane and back to your main dashboard does it fix it for you?
> > 
> > Thanks for your reply. Currently the icon shows up on computer but not on my HA companion app. I tried to got I settings and unfortunately it didn't fit the issue.
> 
> Oh if its companion app,  did you try clearing front end cache via the app settings?
> 
> Settings > Companion App > Troubleshooting (bottom of page) > Reset Frontend cache

That works!! Many thanks for the quick fix.
